### PR TITLE
Howtos, Asciicasting, and programmatic header

### PR DESCRIPTION
**Pull request by eah13**
Adds Howtos section in the header, easy Asciicasting, Asciicasting How-to for TAs & instructors (run `jekyll serve --drafts` and go to how-tos.html to see this), and a programmatically generated header keyed off a list in `_config.yml`.

### CODE REVIEW

**Comment by eah13** [comment]
@gerbal take a look and see if these are working for you.  The Asciicasting is optional but very fun.  I wish there was an easy way to sync audio to them.

If Asciicenma weren't such a pain to install without root I might consider this being a part of the course.  We could script the installation maybe...

Anyways, pls merge if/when you find it worthy.  And feel free to delete the howto branch afterwards.  You'll notice I'm branching inside silshack with these.  seems easier.

**Comment by gerbal** [comment]
@eah13 `pip install --user asciinema` 

I couldn't get your documented deb deconstruction to work properly.

**Comment by eah13** [comment]
Does this let you run the binary?  For me it doesn't/didn't.  pip will dl the library but not add it to our PATH

try `which asciinema` and see what it does for you.

**Comment by gerbal** [comment]
it did for me, using a django-box an not in a Venv

**Comment by eah13** [comment]
oh hmm. wierd. I tried it and It works fine in my virtualenv only.  

OK your instructions are way better.  This is a reason we should install a django box rather than Ruby for students.

Ready for merge if that's the only thing that needed fixing.

**Pull request merged**
