### PR TITLE
Sierra's pull request

### PR DESCRIPTION
**Pull request by eah13**
So we can talk code

### CODE REVIEW

**Comment by eah13** [comment]
@srmoore5 I opened this pull request so we can talk about code.  It's the easiest way to indicate what the bugs are.

The only problem is with file naming.  You have to be very careful with the way you type things: jekyll is very dumb and gets confused easily.  In this case, you have 4 files, all of which have names that Jekyll can't figure out.

Here's some documentation on filenames:
http://jekyllrb.com/docs/posts/

Can you figure out how to fix this?

**Comment by srmoore5** [comment]
I still can not figure out why this post is not displaying.

https://github.com/srmoore5/spring2014/blob/gh-pages/_posts/2014-01-27-pythonbasics.md

Sierra R. Moore
Graduate student
Information Science, 15"
University of North Carolina at Chapel Hill

**Comment by gerbal** [comment]
@srmoore5 Delete the `01-22-2014-sierra_python_exercises.md` file in the root directory

**Comment by eah13** [comment]
Alright I'm merging this in.  Does seem like there's a random picture embedded at the bottom of your post but you're good to go otherwise.

**Comment by srmoore5** [comment]
I chose to post the picture, because I liked it. I thought that it might be a good way to end a post? I should have included a roll-over that indicated this, probably.

**Pull request merged**
