### PR TITLE
Schedules page jumps to current or most recent class.

### PR DESCRIPTION
**Pull request by gerbal**
Should work. We'll see next week if it actually does.

### CODE REVIEW

**Comment by gerbal** [comment]
Well it was working locally, but isn't on my [github pages](http://gerbal.github.io/spring2014/schedule.html#today). Wierdness.

**Comment by gerbal** [comment]
Forgot to include the script in the initial commit, no wonder it didn't work

**Comment by gerbal** [comment]
@eah13 Take a look. http://gerbal.github.io/spring2014/schedule.html#today

**Comment by gerbal** [comment]
I've confirmed this functional in multiple browsers across a range of dates.

**Comment by eah13** [comment]
:necktie: slick!

**Pull request merged**
