### PR TITLE
Create madelinelistsandstrings.md

### PR DESCRIPTION
**Pull request by madeline13**

### CODE REVIEW

**Comment by madeline13** [comment]
https://github.com/silshack/spring2014/pull/203/files

**Comment by eah13** [comment]
Madeline, the link should be to your github.io page.  We discussed this in the hangout.  Let me know if there's any more confusion.

**Comment by eah13** [comment]
The post you created isn't showing up because the filename is incorrectly formatted- should have YYYY-MM-DD- on the front.

**Comment by gerbal** [comment]
This looks good, merging

**Pull request merged**
