### PR TITLE
Thu-Mai's Simple Blog Post

### PR DESCRIPTION
**Pull request by tlchristian**
@eah13 and @gerbal, I finished my Simple Blog post post, but I can't seem to get it up and running on http://tlchristian.github.io/spring2014/.  It shows in my nitrous.io preview, and I did do the "git push origin gh-pages", but no avail.  Not sure what's happening here.  I do have to say that strange things seemed to be happening in my nitrous.io.  For some reason, duplicate sets of folders appeared in my simplehack folder and my spring2014 folder.  Strange?

### CODE REVIEW

**Comment by gerbal** [comment]
Nothing appears to be wrong with your blog post or the commits. You can always test to make sure there are not errors by running a local instance of jekyll. (jekyll serve)

It built fine for me, so it's probably just github pages being very slow to propagate new pages

**Comment by tlchristian** [comment]
Oh, OK. that's good to hear, I guess.  I also updated another post to see if maybe it was just that post.  No update to my website.  I'll go watch True Detectives and see if anything happens after that.  Thanks!

**Comment by tlchristian** [comment]
@gerbal, I should clarify--My class assignment post isn't showing up on http://tlchristian.github.io/spring2014/.  My post on Simple is fine.  I actually did a pull just to see if everything is talking, and it is.  I also made an edit to an older post, which is also not showing up.  I'll just wait a bit like you suggested, but I'm hoping I don't have some connection issues...

**Comment by tlchristian** [comment]
So, I got a Page build error, which reads:

The page build failed with the following error:
The submodule `spring2014` was not properly initialized with a `.gitmodules` file.

It seems that this problem goes beyond this one post; I also updated another post to see if it was my markdown that was the problem.  That other post didn't build either.

**Comment by gerbal** [comment]
By chance is there a spring2014 folder inside your main spring2014 directory?

Git has the ability to have git  repositories inside one another, but they have to be configured in a certain way. If you, say, cloned a git repo inside another git repo, it may cause errors

**Comment by tlchristian** [comment]
There was, then I deleted it.  Same thing happened with my simplehack folder.  And actually, I'm seeing several strange things in my spring2014.  Should I delete spring2014 and pull fresh?

**Comment by gerbal** [comment]
after you delete a folder or file, you have to make sure you tell git about it. you do this using 'git add -all'

**Comment by tlchristian** [comment]
This is what ended up happening when I did that: 
 ! [rejected]        gh-pages -> gh-pages (fetch first)  
error: failed to push some refs to 'https://github.com/tlchristian/spring2014.git'  
hint: Updates were rejected because the remote contains work that you do  
hint: not have locally. This is usually caused by another repository pushing  
hint: to the same ref. You may want to first integrate the remote changes  
hint: (e.g., 'git pull ...') before pushing again.  
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by gerbal** [comment]
So, have you tried doing a 'git pull' to bring your local repository up to date?

**Comment by tlchristian** [comment]
Yes, I did that, too.  It looks fine in Nitrous. I see the new files from the rest of the class.  Btw, I did the git add --all, then pushed, but when I git status, there is still the deleted: spring2014 change to be committed.

Ooh, and now my nitrous preview isn't working.

**Comment by gerbal** [comment]
oh, the changes you made just haven't been commited yet, do a 'git commit -m "deleted duplicate files" or something of the sort.

**Comment by tlchristian** [comment]
Of course!  Yes, now the post is showing up here: http://tlchristian.github.io/spring2014/2014/02/21/ThuMaiSimpleHack.html.  

Still no nitrous preview, but the post is where it's supposed to be.

Thanks for your help!

**Comment by tlchristian** [comment]
@eah13 , I finally got my Doing More with Simple post to work, thanks to Brittany's work-around with the curly bracket spacing.  You can view my post here: http://tlchristian.github.io/spring2014/2014/02/27/ThuMaiSimpleMod.html

**Comment by tlchristian** [comment]
@eah13, I've completed the Pipes and Filters assignment, which you can see here: http://tlchristian.github.io/spring2014/2014/03/07/ThuMaiPipesFilters.html.

**Comment by gerbal** [comment]
@tlchristian, this pull request should be in a new branch

**Comment by tlchristian** [comment]
the pull request is now in a new branch.

**Comment by eah13** [comment]
@tlchristian can you link to that new PR?  I don't see it showing up.

**Pull request merged**
