### PR TITLE
Jessica's Turtle Exercise

### PR DESCRIPTION
**Pull request by jskaa**
http://jskaa.github.io/spring2014/2014/01/17/jessicaturtlepost.html

### CODE REVIEW

**Comment by gerbal** [comment]
@jskaa please link to your github.io pages in your pull request

**Comment by jskaa** [comment]
@gerbal My turtle post isn't showing up in my github.io page. I'm pretty sure there's a step I've forgotten to do, and I can't figure out how to get it to.

**Comment by gerbal** [comment]
@jskaa sometimes github will take a while (A long while) to re-render github.io pages. If the post isn't showing up, then just link to your http://jskaa.github.io/spring2014 instead. We can look for the post if and when github gets its act together.

**Comment by gerbal** [comment]
@jskaa Look at the file name. What is it missing?

**Comment by jskaa** [comment]
Oh, do I need to add .md? I'm not sure how to edit the file name!

**Comment by gerbal** [comment]
Just go to edit the file and you should be able to edit the name

**Comment by eah13** [comment]
@jskaa nice!  A very nice design, and good use of loops.

**Pull request merged**
