### PR TITLE
Oak's About Me Post

### PR DESCRIPTION
**Pull request by Blucka12**
@eah13 @gerbal Here's my post: http://blucka12.github.io/spring2014/2014/02/28/blucka12-herokuaboutme.html

### CODE REVIEW

**Comment by Blucka12** [comment]
@eah13 @gerbal  Question: So [the markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) says that using "~~" before and after makes it appear as though it had been struck through. I tried it both with no spaces and with, and had no luck getting it to show up that way...any suggestions?

**Comment by gerbal** [comment]
@Blucka12 Markdown is pretty finicky so you have this

```
~~ Here's my site: http://silshack-antihero.herokuapp.com/ ~~ #no longer needed, cos I learnt the hyperlinx
~~ It will be different soon! ~~ #It is now, in the present, different...
```

and you should change it into this:

```
~~Here's my site: [http://silshack-antihero.herokuapp.com/](http://silshack-antihero.herokuapp.com/)~~ #no longer needed, cos I learnt the hyperlinx  
~~It will be different soon!~~ #It is now, in the present, different...
```

~~Here's my site: [http://silshack-antihero.herokuapp.com/](http://silshack-antihero.herokuapp.com/)~~ #no longer needed, cos I learnt the hyperlinx  
~~It will be different soon!~~ #It is now, in the present, different...

**Comment by Blucka12** [comment]
Cool. I made those changes and it looks the same to me. You seeing something different? I had that spacing in the first place, @gerbal , but you suggested that I try fiddling with it, which I did...

**Comment by eah13** [comment]
@Blucka12 looks like Jekyll's markdown parser doesn't support strikethrough by default.  I found this: http://stackoverflow.com/questions/17004095/jekyll-markdown-strikethrough

Updated the config.yaml on the main site and it works great.  `git pull upstream gh-pages` and you should have these changes.

Nice work on your post!

**Pull request merged**
