### PR TITLE
Turtle exercise completed

### PR DESCRIPTION
**Pull request by zbay**
Hi, @eah13. I've finished my turtle drawing and have written a post containing it and my code.

### CODE REVIEW

**Comment by eah13** [comment]
@zbay please include a link to your working site

**Comment by zbay** [comment]
@eah13 here is the link to my working site. Do I need to post this in every pull request?
http://zbay.github.io/spring2014/

**Comment by eah13** [comment]
@zbay yes, please do.  The link may change from assignment to assignment and either way it is a reminder to you to check the page.

**Comment by eah13** [comment]
@zbay great work on the image!  Looks great.  Brute force is a great way to go to get started

**Pull request merged**
