### PR TITLE
add post about new console

### PR DESCRIPTION
**Pull request by eah13**
@gerbal see if you can figure out why this post console isn't rendering:
http://trinket-68987.use1.nitrousbox.com:4000/spring2014/2014/01/20/console.html

I'm stumped.

### CODE REVIEW

**Comment by gerbal** [comment]
Well, part of the problem is Jekyll is trying to render the code inside between the includes. So we're getting a bunch of html junk in the python. We may have to start using an include file.py for the code blocks.

The code isn't showing up styled propery because the urls are missing `{{ site.baseurl }}`. For the console.md page it looked in the root directory, so it was fine.

**Comment by gerbal** [comment]
Though we aren't getting scroll bars in the code console box thing, so that's could be a problem.

**Comment by gerbal** [comment]
The codehighlighting should be entirely working now. It puts a ``` code block around the code, then strips the html to prevent stray html elements from crapping up the codeblock. 

Because all of this code relies on the ID attribute of the textarea elements, it breaks with multiple console code blocks. (id's are exclusive and are supposed to be unique).

**Comment by eah13** [comment]
Awesomeness abounds

**Pull request merged**
