### PR TITLE
Added Oak to _config.yml

### LINKED ISSUE #28: OAK needs to update _config.yml
To have him in posts.BOOM.

### LINKED ISSUE #39: OAK needs to make his first post.
So say we all.

### PR DESCRIPTION
**Pull request by Blucka12**
It seems to function.

Fixes #28 
Fixes #39

### CODE REVIEW

**Comment by eah13** [comment]
@Blucka12 net time please remember to include a link to your page:
http://blucka12.github.io/spring2014/

Otherwise looks good!

**Comment by Blucka12** [comment]
@eah13 I looked back, and I put "www.steadyflowblog.com" after "website: " What should I change to connect it properly?

**Comment by gerbal** [comment]
http://www.steadyflowblog.com

**Comment by eah13** [comment]
@Blucka12 ^ this.  It needs to be a link that a browser can read verbatim because the way I wrote the page it dumps the whole thing in.

See also my profile in _config.yml for an example.

**Pull request merged**
