### PR TITLE
Simple blog created and post added

### PR DESCRIPTION
**Pull request by lyonsa**
Here's the link: http://lyonsa.github.io/spring2014/2014/02/24/lyonssimplepost.html

### CODE REVIEW

**Comment by gerbal** [comment]
@lyonsa you should include a link to your simple blog in your github blog post

**Comment by lyonsa** [comment]
Whoops. Forgot :P

---

Allen Lyons
(336)926-1560

**Comment by lyonsa** [comment]
fixed. you can merge now

**Comment by lyonsa** [comment]
Submitted simple about page. Heres a link to that post: http://lyonsa.github.io/spring2014/2014/02/26/lyonsasimpleabout.html

**Comment by eah13** [comment]
Nice work!  Sorry for the delay in merging.

**Pull request merged**
