### PR TITLE
created my pipes exercises post. It's dope. added NCAA. Colab with Grant

### PR DESCRIPTION
**Pull request by babykav**
I couldn't seem to get it to come up on my site, but I've got it done. So if you've got some sort of help with that, that would be great!

### CODE REVIEW

**Comment by eah13** [comment]
@babykav you need an .md on the end of your filename :)

**Comment by eah13** [comment]
Nice work otherwise!

**Comment by eah13** [comment]
Oops I lied.  THis pull request should come from its own branch.  Review the exercise from class if you're unsure how to do this.

**Comment by babykav** [comment]
i added the ncaa one. i'm still working on the other one. nitrous hates me :frowning:

**Pull request closed without merging**
