### PR TITLE
Julie needs to post her 3rd post

### PR DESCRIPTION
**Pull request by juliees39**
http://juliees39.github.io/spring2014/2014/01/24/JuliePythonPost.html

### CODE REVIEW

**Comment by gerbal** [comment]
Please include a link to your Github.io site in the pull request description

**Comment by juliees39** [comment]
@gerbal  Okay, fixed it. Sorry about that.

**Comment by eah13** [comment]
@juliees39 you'll need to add the output of your program in a code block too.  See some of the recently merged posts for an example if you're confused.

**Comment by juliees39** [comment]
@eah13  @gerbal okay, fixed it. Sorry about that.

**Comment by eah13** [comment]
Alright.  Thanks for following up on our comments.

**Pull request merged**
