### PR TITLE
BOTH Haley's Turtle Assignment and Python Basics Post

### PR DESCRIPTION
**Pull request by Gefionne**
Both of my assignments are in here! Just FYI.

### CODE REVIEW

**Comment by eah13** [comment]
@Gefionne have you viewed your post on your site?  Please do so and post the link here.

**Comment by Gefionne** [comment]
I linked it in the Python Basics post, but left it out of the Turtle post. Here are both, just in case:

http://gefionne.github.io/spring2014/2014/01/24/HaleyPythonBasics.html
http://gefionne.github.io/spring2014/2014/01/24/HaleyTurtle.html

**Comment by eah13** [comment]
Thanks for the links- they should be here in the pull request, not in the posts themselves.

I like the 3 versions of exercise 1.  Each of the sections needs input and output.  Take a look at the other posts for examples of this:
http://silshack.github.io/spring2014/

Add those and you're ready to go.

**Comment by Gefionne** [comment]
Oh, that's my bad! Got the inputs and outputs in the post and I'll put the link in the pull request from now on.

**Comment by eah13** [comment]
:boom:  you got it.  Thanks for the speedy fix!

**Pull request merged**
