### PR TITLE
Zach's first blog post

### PR DESCRIPTION
**Pull request by zbay**

### CODE REVIEW

**Comment by gerbal** [comment]
@zbay be sure to link to your post on your github.io site

**Comment by zbay** [comment]
Here's my personal page: http://zbay.github.io/spring2014/

**Comment by zbay** [comment]
Or, rather, the post on my Github: http://zbay.github.io/spring2014/2014/02/20/zbaySimple1.html

**Comment by eah13** [comment]
@zbay Nice work!  You're right that we'll dive into how Heroku works a little more.  Great job following instructions when in doubt.

Whereas with Jekyll we were putting the post data into the code itself, with Simple we're using a much more common (and powerful) architecture where the post data goes into a database running on Heroku.  So the code and the data are separate- posts are created via `/admin` in the app, not via code.

**Pull request merged**
