### PR TITLE
Katie & Laura's NCAA post

### PR DESCRIPTION
**Pull request by katielmeyer**
Added a post describing our process in adding our NCAA teams (Louisville and Kentucky)

### CODE REVIEW

**Comment by eah13** [comment]
@katielmeyer @Lasher09 remember to move the Louisville and Kentucky files into the correct folder.

**Comment by katielmeyer** [comment]
@eah13  The pull request with that change is sitting over in the NCAA repo (https://github.com/silshack/NCAA/pull/36). Would you be able to merge it? Or can I go ahead and merge my own pull request without breaking too many taboos?

**Comment by gerbal** [comment]
@katielmeyer it's OK to merge in pull requests that fix outstanding errors you have identified. Especially for small changes. The best way to do it would to be to get someone else to merge it though. 

I'll go ahead and merge silshack/NCAA#36

**Comment by katielmeyer** [comment]
Thank you!

**Comment by eah13** [comment]
Nice work!  and thanks for fixing that.

**Pull request merged**
