### PR TITLE
Create 2014-01-30-sunhwastring&list.md

### PR DESCRIPTION
**Pull request by sunhwap**
I finished string and list exercises.
Here is my link: http://sunhwap.github.io/spring2014/2014/01/30/sunhwa%27sstring%26list.html

### CODE REVIEW

**Comment by gerbal** [comment]
Just an FYI, special characters in file names don't agree with all browsers and webservers. The actual link to your post is here: http://sunhwap.github.io/spring2014/2014/01/30/sunhwa%27sstring%26list.html

**Comment by sunhwap** [comment]
Ok. got it.so do I have to edit the link in the github?Thanks. Grant.sunhwa

Date: Thu, 30 Jan 2014 14:14:05 -0800

**Comment by gerbal** [comment]
Change the link in the pull request description to the working one. Other than that you're fine.

**Comment by sunhwap** [comment]
Thank you, Grant.
Sunhwa

**Comment by sunhwap** [comment]
Hi Grant,I forgot how to change the link in the pull request.could you describe it for me?sorry about this.thank you.Sunhwa

Date: Thu, 30 Jan 2014 14:38:13 -0800

**Comment by gerbal** [comment]
on the pull request page click the pencil icon on a post to edit its contents.

**Comment by sunhwap** [comment]
Thank you so much, Grant.sunhwa

Date: Thu, 30 Jan 2014 17:36:03 -0800

**Comment by eah13** [comment]
Nice work.  Thanks @gerbal as well.

**Pull request merged**
