### PR TITLE
code for my turtle

### PR DESCRIPTION
**Pull request by bdferr**
This is the long code for my turtle image. Should I shorten it with more "for" loops? Here is my gitub.io page: http://bdferr.github.io/spring2014/

### CODE REVIEW

**Comment by gerbal** [comment]
Could you link to your github.io page in the pull request description?

**Comment by bdferr** [comment]
Alright, done.

-Brendan Ferreri-Hanberry

**Comment by gerbal** [comment]
It looks like your two posts are identical, pick one and delete the other. 

In the future if you want to change an existing post you don't need to make a new one, just change the old one.

**Comment by bdferr** [comment]
Grant,

No, as I state in the comments, one of them does not have the proper image link. I have just deleted the earlier one though. Also I can see the image rendered fine at 2014-01-15-bdferrturtle2.md, so I am not sure if you are right about the line break; maybe you are just looking at the older post? I have added it anyway though.

-Brendan

**Comment by gerbal** [comment]
it looks good now. Because of the vagaries of Jekyll and github your turtle post wasn't showing up for me. It is showing now.

**Comment by eah13** [comment]
@bdferr nice work gettting this up.

You asked whether you should shorten the code: it would definitely be a great learning exercise!  Try it out.

But it looks like the post is looking great thanks to @gerbal's help.

**Pull request merged**
