### PR TITLE
Julie needs to post List and Strings exercises

### PR DESCRIPTION
**Pull request by juliees39**
Here is the link to my post: https://github.com/juliees39/spring2014/blob/gh-pages/_posts/2014-01-31stringlists.md

I am having trouble figuring out the string exercises. Also, the last list exercise.

### CODE REVIEW

**Comment by eah13** [comment]
@juliees39 The link you left is to your github.com site, not the github.io site.  If you go to the latter you'll see it's not rendering correctly due to the filename not having the correct format.  Take a look at some of the closed pull requests if you're still confused.

**Comment by juliees39** [comment]
@eah13 Okay fixed it. Sorry
here's the link: http://juliees39.github.io/spring2014/2014/01/31/stringlists.html
And the general site: http://juliees39.github.io/spring2014

**Comment by eah13** [comment]
@juliees39 I'm going to go ahead and merge this so you don't get behind.  Take a look at some of the other code for the replace function (and/or revisit it after some codingbat practice).  You're close to the solution here.  Also feel free to schedule some time with me if you'd like one-on-one

**Comment by juliees39** [comment]
@eah13 Hi, yes, when would be a good time to do that? I've read through the Strings reading a couple of times and still can't figure out the exercises.

**Pull request merged**
