### PR TITLE
Created my turtle file

### PR DESCRIPTION
**Pull request by madeline13**
I'm not sure what happened there.

### CODE REVIEW

**Comment by gerbal** [comment]
@madeline13 please link to your github.io page

**Comment by gerbal** [comment]
@madeline13 problem 1: the file is not named .md. Problem 2, flickr doesn't play well with embedded images. Try using something like http://imgur.com

**Comment by gerbal** [comment]
@madeline13 please link to your github.io page in the pull request description

**Comment by eah13** [comment]
@madeline13 looks like you've not yet merged in changes from the silshack repository into your site.  Here's the link to that exercise if you need it:
http://silshack.github.io/spring2014/how-to/exercise/2014/01/20/ghmerging.html

Regarding the links that @gerbal was referring to, they should be in the pull request description, which is at the top of the page and currently says "I'm not sure what happened here".  You can edit that when you click the 'Edit' button.

**Comment by eah13** [comment]
@madeline13 see my comments above and let's talk if you're confused.  Still a decent amount of work to do before this is ready to merge.

**Comment by gerbal** [comment]
@madeline13 If you think this is ready to be merged, let us know.

**Comment by eah13** [comment]
Closing this in favor of #203

**Pull request closed without merging**
