### PR TITLE
added timezone to config.yml

### PR DESCRIPTION
**Pull request by gerbal**
Should make build-date on pages EDT

### CODE REVIEW

**Comment by eah13** [comment]
Awesome!  works great.

Might be slick if we could endow prof. jekyll with the ability to localize to the user's timezone...  I'll open an issue for that.

**Comment by eah13** [comment]
Haha nice you merged this just as I commented and was about to.

**Comment by gerbal** [comment]
Totally can make that happen javascript to the rescue. Probably 2 lines of code in a little script box.

**Comment by gerbal** [comment]
@eah13 see #188

**Pull request merged**
