### PR TITLE
Improved console: Removed pythonanywhere and added basic skulpt

### PR DESCRIPTION
**Pull request by eah13**
Still needs work to run Turtle.  But it's python!  Client side!   

This pulls from the `_includes` I added before via sneaky/sloppy commits.

@gerbal this is all you.  OK to delete branch after merge.

### CODE REVIEW

**Comment by gerbal** [comment]
Doesn't throw any error messages for malformed python. Just breaks silently.

**Comment by eah13** [comment]
Our textbook takes errors and parses them into a special div.  Same thing with turtle graphics.  It'll take a little more work to get this as clean as theirs is without bogging down the whole site (they load LOTS of javascript).  

Think you could figure out how they do this and add an error div and formatting?  I've actually got a call this week with the author of the textbook site and I'll see if I can learn about how they do this.  The docs aren't great.

**Comment by gerbal** [comment]
I'll look into it. We can probably just load the js in the Include.

**Comment by gerbal** [comment]
well, it works good-enough for the moment, I'll take a look at it later this week and see how far I can spread my javascript wings.

Merging :shipit:

**Pull request merged**
