### PR TITLE
Oak's Codingbat 2 Assignment

### PR DESCRIPTION
**Pull request by Blucka12**
http://blucka12.github.io/spring2014/

### CODE REVIEW

**Comment by eah13** [comment]
@Blucka12 preview link?  Have you verified the code works?

**Comment by Blucka12** [comment]
Just added the final screenshot confirming success!

**Comment by eah13** [comment]
@Blucka12 Need a github.io link in this pull request: you know the drill!

**Comment by eah13** [comment]
@gerbal any idea why there are all sorts of old changes showing up in his diff?  seems like a Github bug.

**Comment by gerbal** [comment]
@eah13 I think you're right. I've had this happen to me. I think github us seeing the commit created by pulling in a remote as a normal commit

**Comment by eah13** [comment]
@Blucka12 you've got outstanding issues on this pull request, which means your Heroku post is getting wrapped up into it as well.  Please resolve issues on open pull requests quickly so this doesn't happen in the future.  See several comments in this thread

**Comment by Blucka12** [comment]
Ok, I added the io link to the post. Anything else I'm missing? Did the source of the other bugs become clear?

**Comment by eah13** [comment]
Oh OK I think I see the misunderstanding.  The preview link shold be in the pull request description.  Yours (top of this page) is currently empty:

screenshot 2014-02-23 at 12 47 05 pm

That's what I meant to say here:

> @Blucka12 Need a github.io link in this pull request: you know the drill!

Take a look at some of the closed pull requests for an example.

**Comment by Blucka12** [comment]
Ah yes!
Here's the io link:

http://blucka12.github.io/spring2014/2014/02/16/blucka12-codingbat2.html

**Comment by gerbal** [comment]
@eah13 @Blucka12 it looks like all the outstanding issues with this pull request have been resolved. I'll open some issues so we can flag this as fulfilling other requirements and then merge it.

**Comment by gerbal** [comment]
Fixes #305 
Fixes #306

**Pull request merged**
